title: Profile Weather View
description: Automated weather updates for your GitHub profile
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

# Enable GitHub flavored markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enable relative links
relative_links:
  enabled: true
  collections: true

# Directory structure
include:
  - 'src/docs'

# Convert markdown files to HTML
defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'

# GitHub information
github:
  is_project_page: true
  repository_url: https://github.com/tashfiqul-islam/profile-weather-view
  owner_name: Tashfiqul Islam
  owner_url: https://github.com/tashfiqul-islam

# Navigation (for custom themes that support it)
nav:
  - Home: index.html
  - Getting Started: src/docs/getting-started.html
  - Architecture: src/docs/architecture.html
  - API Reference: src/docs/api-reference.html
  - Configuration: src/docs/configuration.html
  - Deployment: src/docs/deployment.html
  - Testing: src/docs/testing.html
  - Contributing: src/docs/contributing.html
  - Troubleshooting: src/docs/troubleshooting.html
