# ============================================================
# 🤖 Dependabot Configuration
# ============================================================
# Automated dependency updates with intelligent versioning control

version: 2
updates:
  # -------------------------------------------------------
  # 📦 npm Package Dependencies (Including Bun)
  # -------------------------------------------------------
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Dhaka"
    versioning-strategy: "auto"
    target-branch: "master"
    open-pull-requests-limit: 15
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "npm"
      - "security"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      prefix-development: "chore"
      include: "scope"
    assignees:
      - "tashfiqul-islam"
    reviewers:
      - "tashfiqul-islam"
    rebase-strategy: "auto"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      bun-runtime:
        patterns:
          - "bun"
          - "bun-types"
          - "@types/bun"
        update-types:
          - "minor"
          - "patch"
      eslint-plugins:
        patterns:
          - "*eslint*"
        update-types:
          - "minor"
          - "patch"
      test-dependencies:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "minor"
          - "patch"

  # -------------------------------------------------------
  # 🔄 GitHub Actions
  # -------------------------------------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Dhaka"
    target-branch: "master"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "ci"
      include: "scope"
    assignees:
      - "tashfiqul-islam"
    groups:
      actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
